FROM ubuntu:jammy

RUN set -xe; \
    export DEBIAN_FRONTEND=noninteractive; \
    apt-get update; \
    apt-get install -y build-essential cmake; \
    apt-get clean;

WORKDIR /app

# Since CI runs with Docker-in-Docker, we can't just mount a volume...
COPY . /app
